echo 'train with wmt15 and test with 16'
echo '############################################# 0 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 0 -verbose
echo '############################################# 1 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 1 -verbose
echo '############################################# 2 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 2 -verbose
echo '############################################# 3 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 3 -verbose
echo '############################################# 4 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 4 -verbose
echo '############################################# 5 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 5 -verbose
echo '############################################# 6 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 6 -verbose
echo '############################################# 7 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 7 -verbose
echo '############################################# 8 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 8 -verbose
echo '############################################# 9 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 9 -verbose
echo '############################################# 10 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 10 -verbose
echo '############################################# 11 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 11 -verbose
echo '############################################# 12 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 12 -verbose
echo '############################################# 13 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 13 -verbose
echo '############################################# 14 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 14 -verbose
echo '############################################# 15 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 15 -verbose
echo '############################################# 16 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 16 -verbose
echo '############################################# 17 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_2015_deen_s1 -tgt_s2 /tmp/decMixture_2015_deen_s2 -tgt_ref /tmp/decMixture_2015_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 17 -verbose






echo 'train with wmt1415 and test with 15'

echo '############################################# 0 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 0 -verbose
echo '############################################# 1 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 1 -verbose
echo '############################################# 2 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 2 -verbose
echo '############################################# 3 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 3 -verbose
echo '############################################# 4 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 4 -verbose
echo '############################################# 5 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 5 -verbose
echo '############################################# 6 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 6 -verbose
echo '############################################# 7 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 7 -verbose
echo '############################################# 8 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 8 -verbose
echo '############################################# 9 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 9 -verbose
echo '############################################# 10 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 10 -verbose
echo '############################################# 11 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 11 -verbose
echo '############################################# 12 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 12 -verbose
echo '############################################# 13 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 13 -verbose
echo '############################################# 14 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 14 -verbose
echo '############################################# 15 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 15 -verbose
echo '############################################# 16 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 16 -verbose
echo '############################################# 17 #########################################################################'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_20145_deen_s1 -tgt_s2 /tmp/decMixture_20145_deen_s2 -tgt_ref /tmp/decMixture_20145_deen_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2015/data_scores_sum -test_s1 /tmp/decMixture_2016_deen_s1 -test_s2 /tmp/decMixture_2016_deen_s2 -test_ref /tmp/decMixture_2016_deen_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_source_rank_de.en/extracted_data_2016/data_scores -cand 17 -verbose

