"""
Do_da.sh is the code to get the embedding
Do_da2.sh is the code to train the model but hold the distance function for direct distance based model
Do_da3.sh is the code to train the model but hold the aggregation function for direct distance based model
Do_da4.sh is the code to train the model but hold the distance function for mapped distance based model
Do_da5.sh is the code to train the model but hold the aggregation function for mapped distance based model
"""


echo '######################'
echo '### distance ###########'
echo '######################'
echo 'with the order, max-mean-sum'
echo '***** w2v *****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type L1
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type L2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type cos
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type braycurtis
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type canberra
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type chebyshev
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type correlation
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type minkowski
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type mulsum

echo '***** w2v-slim *****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type L1
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type L2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type cos
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type braycurtis
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type canberra
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type chebyshev
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type correlation
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type minkowski
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -type mulsum

echo '**** encoderEmbd ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type L1
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type L2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type cos
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type braycurtis
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type canberra
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type chebyshev
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type correlation
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type minkowski
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type mulsum

echo '**** decoderEmbd Mix ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type L1
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type L2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type cos
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type braycurtis
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type canberra
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type chebyshev
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type correlation
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type minkowski
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1 -type mulsum

echo '**** decoder Out Mix ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 4 -type L1
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 4 -type L2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 4 -type cos
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 4 -type braycurtis
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 4 -type canberra
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 4 -type chebyshev
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 4 -type correlation
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 4 -type minkowski
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 4 -type mulsum

echo '**** decoder states 1 ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 8 -type L1
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 8 -type L2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 8 -type cos
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 8 -type braycurtis
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 8 -type canberra
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 8 -type chebyshev
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 8 -type correlation
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 8 -type minkowski
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 8 -type mulsum

echo '**** decoder states 2 ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 9 -type L1
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 9 -type L2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 9 -type cos
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 9 -type braycurtis
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 9 -type canberra
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 9 -type chebyshev
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 9 -type correlation
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 9 -type minkowski
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 9 -type mulsum

echo '**** decoder Ceils 1 ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 14 -type L1
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 14 -type L2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 14 -type cos
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 14 -type braycurtis
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 14 -type canberra
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 14 -type chebyshev
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 14 -type correlation
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 14 -type minkowski
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 14 -type mulsum

echo '**** decoder Ceils 2 ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 15 -type L1 
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 15 -type L2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 15 -type cos 
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 15 -type braycurtis
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 15 -type canberra
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 15 -type chebyshev
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 15 -type correlation
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 15 -type minkowski
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 15 -type mulsum


