#"""
#Do_da.sh is the code to get the embedding
#Do_da2.sh is the code to train the model but hold the distance function
#"""

echo '######################'
echo '### mepper ###########'
echo '######################'
echo 'with the order, max-mean-sum'
echo '***** w2v *****'
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_sys_max.npy -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_ref_max.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_mean.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_mean.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_sys_mean.npy -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_ref_mean.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_sum.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_sum.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_sys_sum.npy -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_ref_sum.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose
echo '***** w2v-slim *****'
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_sys_slim_max.npy -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_ref_slim_max.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_mean.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_mean.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_sys_slim_mean.npy -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_ref_slim_mean.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_sum.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_sum.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_sys_slim_sum.npy -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_ref_slim_sum.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose
echo '**** encoderEmbd ****'
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2017_mix_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2017_mix_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 1 -num_dim 500
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2017_mix_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2017_mix_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 2 -num_dim 500
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2017_mix_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2017_mix_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 0 -num_dim 500
echo '**** decoderEmbd Mix ****'
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 1 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 2 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 0 -num_dim 500 
echo '**** decoder Out Mix ****'
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 4 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 5 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 3 -num_dim 500 
echo '**** decoder states 1 ****'
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 8 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 10 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 6 -num_dim 500 
echo '**** decoder states 2 ****'
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 9 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 11 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 7 -num_dim 500 
echo '**** decoder Ceils 1 ****'
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 14 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 16 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 12 -num_dim 500 
echo '**** decoder Ceils 2 ****'
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 15 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 17 -num_dim 500 
#python experiments/train_model_da_mepper.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016.de-en -test_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_sys -test_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2017_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 -verbose -cand 13 -num_dim 500 





echo '######################'
echo '### distance ###########'
echo '######################'
echo 'with the order, max-mean-sum'
echo '***** w2v *****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_mean.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_mean.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_sum.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_sum.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 
echo '***** w2v-slim *****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_mean.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_mean.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_sys_slim_sum.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2016_ref_slim_sum.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 
echo '**** encoderEmbd ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/encoder/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 0 
echo '**** decoderEmbd Mix ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 1
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 2
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 0
echo '**** decoder Out Mix ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 4
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 5
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 3
echo '**** decoder states 1 ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 8
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 10
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 6
echo '**** decoder states 2 ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 9
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 11
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 7
echo '**** decoder Ceils 1 ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 14
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 16
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 12
echo '**** decoder Ceils 2 ****'
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 15
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 17
python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_sys -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/decoder/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2016 -cand 13












#python experiments/train_model_da_distance.py -tgt_s1 /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_sys_max.npy -tgt_ref /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/w2v/w2v_deen_2017_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_da_de.en/data_scores_2017 

