echo 
echo '### direct ###########'
echo '######################'
echo 'with the order, max-mean-sum'
echo '***** w2v *****'
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type L1
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type L2
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type braycurtis
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type canberra
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type chebyshev
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type correlation 
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type minkowski

echo '***** w2v-slim *****'
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_slim_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_slim_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_slim_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type L1
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_slim_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_slim_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_slim_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type L2
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_slim_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_slim_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_slim_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_slim_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_slim_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_slim_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type braycurtis
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_slim_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_slim_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_slim_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type canberra
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_slim_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_slim_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_slim_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type chebyshev
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_slim_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_slim_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_slim_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type correlation
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/w2v_slim_deen_2016_s1_max.npy -tgt_s2 /tmp/w2v_slim_deen_2016_s2_max.npy -tgt_ref /tmp/w2v_slim_deen_2016_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -type minkowski

echo '***** encoderEmbd *****'
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/encoderEmb_deen_2016_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2016_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type L1
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/encoderEmb_deen_2016_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2016_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type L2
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/encoderEmb_deen_2016_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2016_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/encoderEmb_deen_2016_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2016_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type braycurtis
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/encoderEmb_deen_2016_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2016_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type canberra
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/encoderEmb_deen_2016_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2016_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type chebyshev
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/encoderEmb_deen_2016_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2016_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type correlation
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/encoderEmb_deen_2016_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2016_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2016_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type minkowski

echo '***** decoderEmbd *****'
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type L1
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type L2
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type braycurtis
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type canberra
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type chebyshev
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type correlation
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type minkowski

echo '***** decoderEmbd *****'
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type L1
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type L2
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type braycurtis
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type canberra
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type chebyshev
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type correlation
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 1 -type minkowski

echo '***** decoderOut *****'
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 4 -type L1
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 4 -type L2
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 4 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 4 -type braycurtis
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 4 -type canberra
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 4 -type chebyshev
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 4 -type correlation
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 4 -type minkowsk

echo '***** decoderState1 *****'
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 8 -type L1
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 8 -type L2
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 8 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 8 -type braycurtis
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 8 -type canberra
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 8 -type chebyshev
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 8 -type correlation
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 8 -type minkowski

echo '***** decoderState2 *****'
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 9 -type L1
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 9 -type L2
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 9 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 9 -type braycurtis
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 9 -type canberra
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 9 -type chebyshev
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 9 -type correlation
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 9 -type minkowski

echo '***** decoderCeil1 *****'
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 14 -type L1
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 14 -type L2
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 14 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 14 -type braycurtis
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 14 -type canberra
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 14 -type chebyshev
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 14 -type correlation
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 14 -type minkowsik

echo '***** decoderCeil2 *****'
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 15 -type L1
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 15 -type L2
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 15 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 15 -type cos
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 15 -type braycurtis
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 15 -type canberra
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 15 -type chebyshev
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 15 -type correlation
python experiments/train_model_rr_distance.py -tgt_s1 /tmp/decMixture_deen_2016_s1 -tgt_s2 /tmp/decMixture_deen_2016_s2 -tgt_ref /tmp/decMixture_deen_2016_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -cand 15 -type minkowski

