"""
Do_rr2: script for distance based model direct model: train_model_rr_distance 
Do_rr3: script for distance based model mapped model: Simple6
Do_rr4: script for neural based model 1 output model: Simple9
Do_rr5: script for neural based model 3 output model: train_model-Simple0
Do_rr6: script for neural based model half model: Simple1
Do_rr7: script for neural based model mul model: Simpoe2
"""

echo '######################'
echo '### direct ###########'
echo '######################'
echo 'with the order, max-mean-sum'
echo '***** w2v *****'
python experiments/train_model2.py -tgt_s1 /tmp/w2v_deen_2015_s1_max.npy -tgt_s2 /tmp/w2v_deen_2015_s2_max.npy -tgt_ref /tmp/w2v_deen_2015_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -test_s1 /tmp/w2v_deen_2016_s1_max.npy -test_s2 /tmp/w2v_deen_2016_s2_max.npy -test_ref /tmp/w2v_deen_2016_ref_max.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped
python experiments/train_model2.py -tgt_s1 /tmp/w2v_deen_2015_s1_mean.npy -tgt_s2 /tmp/w2v_deen_2015_s2_mean.npy -tgt_ref /tmp/w2v_deen_2015_ref_mean.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -test_s1 /tmp/w2v_deen_2016_s1_mean.npy -test_s2 /tmp/w2v_deen_2016_s2_mean.npy -test_ref /tmp/w2v_deen_2016_ref_mean.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped
python experiments/train_model2.py -tgt_s1 /tmp/w2v_deen_2016_s1_sum.npy -tgt_s2 /tmp/w2v_deen_2016_s2_sum.npy -tgt_ref /tmp/w2v_deen_2016_ref_sum.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -test_s1 /tmp/w2v_deen_2016_s1_sum.npy -test_s2 /tmp/w2v_deen_2016_s2_sum.npy -test_ref /tmp/w2v_deen_2016_ref_sum.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped
echo '***** w2v-slim *****'
python experiments/train_model2.py -tgt_s1 /tmp/w2v_slim_deen_2015_s1_max.npy -tgt_s2 /tmp/w2v_slim_deen_2015_s2_max.npy -tgt_ref /tmp/w2v_slim_deen_2015_ref_max.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -test_s1 /tmp/w2v_slim_deen_2016_s1_max.npy -test_s2 /tmp/w2v_slim_deen_2016_s2_max.npy -test_ref /tmp/w2v_slim_deen_2016_ref_max.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped
python experiments/train_model2.py -tgt_s1 /tmp/w2v_slim_deen_2015_s1_mean.npy -tgt_s2 /tmp/w2v_slim_deen_2015_s2_mean.npy -tgt_ref /tmp/w2v_slim_deen_2015_ref_mean.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -test_s1 /tmp/w2v_slim_deen_2016_s1_mean.npy -test_s2 /tmp/w2v_slim_deen_2016_s2_mean.npy -test_ref /tmp/w2v_slim_deen_2016_ref_mean.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped
python experiments/train_model2.py -tgt_s1 /tmp/w2v_slim_deen_2015_s1_sum.npy -tgt_s2 /tmp/w2v_slim_deen_2015_s2_sum.npy -tgt_ref /tmp/w2v_slim_deen_2015_ref_sum.npy -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -test_s1 /tmp/w2v_slim_deen_2016_s1_sum.npy -test_s2 /tmp/w2v_slim_deen_2016_s2_sum.npy -test_ref /tmp/w2v_slim_deen_2016_ref_sum.npy -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped
echo '***** encoderEmbd *****'
python experiments/train_model2.py -tgt_s1 /tmp/encoderEmb_deen_2015_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2015_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2015_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 1 -test_s1 /tmp/encoderEmb_deen_2016_mix_s1 -test_s2 /tmp/encoderEmb_deen_2016_mix_s2 -test_ref /tmp/encoderEmb_deen_2016_mix_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/encoderEmb_deen_2015_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2015_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2015_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -test_s1 /tmp/encoderEmb_deen_2016_mix_s1 -test_s2 /tmp/encoderEmb_deen_2016_mix_s2 -test_ref /tmp/encoderEmb_deen_2016_mix_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500 -cand 2
python experiments/train_model2.py -tgt_s1 /tmp/encoderEmb_deen_2015_mix_s1 -tgt_s2 /tmp/encoderEmb_deen_2015_mix_s2 -tgt_ref /tmp/encoderEmb_deen_2015_mix_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 0 -test_s1 /tmp/encoderEmb_deen_2016_mix_s1 -test_s2 /tmp/encoderEmb_deen_2016_mix_s2 -test_ref /tmp/encoderEmb_deen_2016_mix_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500

echo '***** decoderEmbd *****'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 1 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 2 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 0 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
echo '***** decoderOut *****'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 4 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 5 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 3 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
echo '***** decoderState1 *****'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 8 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 10 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 6 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
echo '***** decoderState2 *****'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 9 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 11 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 7 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
echo '***** decoderCeil1 *****'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 14 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 16 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 12 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
echo '***** decoderCeil2 *****'
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 15 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 17 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500
python experiments/train_model2.py -tgt_s1 /tmp/decMixture_deen_2015_s1 -tgt_s2 /tmp/decMixture_deen_2015_s2 -tgt_ref /tmp/decMixture_deen_2015_ref -scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2015 -cand 13 -test_s1 /tmp/decMixture_deen_2016_s1 -test_s2 /tmp/decMixture_deen_2016_s2 -test_ref /tmp/decMixture_deen_2016_ref -test_scores /Users/ihuangyiran/Documents/Workplace_Python/data/MasterArbeit/plan_c_rank_de.en/data_scores_2016 -model mapped -num_dim 500



#./Do_rr4.sh
#./Do_rr5.sh
#./Do_rr6.sh
#./Do_rr7.sh

